### ISSUE TITLE
Output path parameter

### ISSUE THREAD

**Issue by mcdeo1996** [FriedrichWeinmann/PSAzureMigrationAdvisor#8]
Can you add an output path parameter for the 'convert' function? Then there would be a copy of the converted files without modifying the originals. This would save a step for engineers to have to copy the files, then run the convert against safely. 

Thank you.

Mike

**Comment by FriedrichWeinmann** [comment]
Hey Mike,
sorry about the delay, but v1.1.8 has that implemented.
Release pipeline running right now, by the time you get this notification it should be live in the gallery :)
